In [67]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.12/site-packages (2.9.10)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.12/site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy) (4.11.0)
Note: you may need to restart the kernel to use updated packages.

In [68]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
import re
from sqlalchemy import create_engine

In [69]:
data = pd.read_csv("/Users/s.v.ssaisreenivas/projects/Data analysis/Marketing analysis/Marketing campaign dataset.csv", header=0)

In [70]:
# .iloc[:, :] --> first represents rows second represent columns;

In [71]:
data.iloc[ :, :20].head()

,campaign_item_id,no_of_days,time,ext_service_id,ext_service_name,creative_id,creative_width,creative_height,search_tags,template_id,landing_page,advertiser_id,advertiser_name,network_id,approved_budget,advertiser_currency,channel_id,channel_name,max_bid_cpm,network_margin
0,2733,7,2022-05-01,128,Facebook Ads,1000,300.0,250.0,#The Power of X,90.0,https://www.abcjewelry.com/collections/boho-je...,4756,Web,190,400.0,SGD,32,Mobile,NaN,0.0
1,2733,8,2022-05-02,16,DV360,1000,300.0,250.0,#Be Bold. Be X,90.0,https://www.abcjewelry.com/women/costume-jewelry/,4756,Web,190,400.0,SGD,8,Social,NaN,0.0
2,2733,9,2022-05-03,128,Facebook Ads,1000,300.0,250.0,#Embrace Your Individuality with X,90.0,https://www.abcjewelry.com/collections/boho-je...,4756,Web,190,400.0,SGD,8,Social,NaN,0.0
3,2733,10,2022-05-04,128,Facebook Ads,1000,300.0,250.0,#Be Bold. Be X,90.0,https://www.abcjewelry.com/collections/rhinest...,4756,Web,190,400.0,SGD,64,Video,NaN,0.0
4,2733,11,2022-05-05,4,Google Ads,1000,300.0,250.0,#Be Bold. Be X,90.0,https://www.abcjewelry.com/collections/boho-je...,4756,Web,190,400.0,SGD,32,Mobile,NaN,0.0

In [72]:
data.iloc[ :, :20].tail()

,campaign_item_id,no_of_days,time,ext_service_id,ext_service_name,creative_id,creative_width,creative_height,search_tags,template_id,landing_page,advertiser_id,advertiser_name,network_id,approved_budget,advertiser_currency,channel_id,channel_name,max_bid_cpm,network_margin
72607,3567,11,2022-11-28,4,Google Ads,15605,NaN,NaN,#The X Factor - Fashion for the Fearless,NaN,https://www.abcjewelry.com/women/vintage-inspi...,6304,UP,353,442054.0,INR,32,Mobile,1.0,0.0
72608,3567,12,2022-11-29,128,Facebook Ads,15605,NaN,NaN,#Embrace Your Individuality with X,NaN,https://www.abcjewelry.com/collections/boho-je...,6304,UP,353,442054.0,INR,4,Search,1.0,0.0
72609,3567,13,2022-11-30,128,Facebook Ads,15605,NaN,NaN,#The Power of X,NaN,https://www.abcjewelry.com/women/affordable-je...,6304,UP,353,442054.0,INR,64,Video,1.0,0.0
72610,3567,14,2022-12-01,4,Google Ads,15605,NaN,NaN,#Embrace Your Individuality with X,NaN,https://www.abcjewelry.com/collections/bold-je...,6304,UP,353,442054.0,INR,8,Social,1.0,0.0
72611,3567,15,2022-12-02,16,DV360,15605,NaN,NaN,#Be Bold. Be X,NaN,https://www.abcjewelry.com/collections/long-ne...,6304,UP,353,442054.0,INR,64,Video,1.0,0.0

In [73]:
data.iloc[ :, 20:].head()

,campaign_budget_usd,impressions,clicks,stats_currency,currency_code,exchange_rate,media_cost_usd,position_in_content,unique_reach,total_reach,search_tag_cat,cmi_currency_code,timezone,weekday_cat,keywords
0,652.173913,837,8,SGD,SGD,1,14.058514,NaN,NaN,NaN,Others,SGD,Asia/Singapore,week_end,delicate bracelets
1,652.173913,2634,44,SGD,SGD,1,99.633496,NaN,NaN,NaN,Others,SGD,Asia/Singapore,week_day,summer jewelry
2,652.173913,2135,32,SGD,SGD,1,109.419677,NaN,NaN,NaN,Others,SGD,Asia/Singapore,week_day,artisan jewelry
3,652.173913,2327,48,SGD,SGD,1,115.209499,NaN,NaN,NaN,Others,SGD,Asia/Singapore,week_day,layered bracelets
4,652.173913,1538,20,SGD,SGD,1,66.990104,NaN,NaN,NaN,Others,SGD,Asia/Singapore,week_day,minimalist jewelry

In [74]:
data.iloc[ :, 20:].tail()

,campaign_budget_usd,impressions,clicks,stats_currency,currency_code,exchange_rate,media_cost_usd,position_in_content,unique_reach,total_reach,search_tag_cat,cmi_currency_code,timezone,weekday_cat,keywords
72607,306.635594,1059,56,INR,INR,1,4.858090,NaN,NaN,NaN,Others,INR,Asia/Kolkata,week_day,chic jewelry
72608,306.635594,865,41,INR,INR,1,3.536262,NaN,NaN,NaN,Others,INR,Asia/Kolkata,week_day,statement pins
72609,306.635594,646,21,INR,INR,1,1.947816,NaN,NaN,NaN,Others,INR,Asia/Kolkata,week_day,bridal jewelry
72610,306.635594,658,20,INR,INR,1,1.711467,NaN,NaN,NaN,Others,INR,Asia/Kolkata,week_day,jewelry sets
72611,306.635594,600,14,INR,INR,1,0.990870,NaN,NaN,NaN,Others,INR,Asia/Kolkata,week_day,fall jewelry

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72612 entries, 0 to 72611
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   campaign_item_id     72612 non-null  int64
 1   no_of_days           72612 non-null  int64
 2   time                 72612 non-null  object
 3   ext_service_id       72612 non-null  int64
 4   ext_service_name     72612 non-null  object
 5   creative_id          72612 non-null  int64
 6   creative_width       69200 non-null  float64
 7   creative_height      69200 non-null  float64
 8   search_tags          72612 non-null  object
 9   template_id          69200 non-null  float64
 10  landing_page         72612 non-null  object
 11  advertiser_id        72612 non-null  int64
 12  advertiser_name      72612 non-null  object
 13  network_id           72612 non-null  int64
 14  approved_budget      72206 non-null  float64
 15  advertiser_currency  72612 non-null  object
 16  channel_id           72612 non-null  int64
 17  channel_name         72612 non-null  object
 18  max_bid_cpm          7406 non-null   float64
 19  network_margin       72612 non-null  float64
 20  campaign_budget_usd  72612 non-null  float64
 21  impressions          72612 non-null  int64
 22  clicks               72612 non-null  int64
 23  stats_currency       72612 non-null  object
 24  currency_code        72612 non-null  object
 25  exchange_rate        72612 non-null  int64
 26  media_cost_usd       72612 non-null  float64
 27  position_in_content  0 non-null      float64
 28  unique_reach         0 non-null      float64
 29  total_reach          0 non-null      float64
 30  search_tag_cat       72612 non-null  object
 31  cmi_currency_code    72612 non-null  object
 32  timezone             72612 non-null  object
 33  weekday_cat          72612 non-null  object
 34  keywords             72612 non-null  object
dtypes: float64(11), int64(10), object(14)
memory usage: 19.4+ MB

In [76]:
zero_counts = (data == 0).sum()
zero_counts

campaign_item_id           0
no_of_days              1843
time                       0
ext_service_id             0
ext_service_name           0
creative_id                0
creative_width          7425
creative_height         7425
search_tags                0
template_id                0
landing_page               0
advertiser_id              0
advertiser_name            0
network_id                 0
approved_budget            0
advertiser_currency        0
channel_id                 0
channel_name               0
max_bid_cpm                0
network_margin         72612
campaign_budget_usd        0
impressions                0
clicks                     0
stats_currency             0
currency_code              0
exchange_rate              0
media_cost_usd           282
position_in_content        0
unique_reach               0
total_reach                0
search_tag_cat             0
cmi_currency_code          0
timezone                   0
weekday_cat                0
keywords                   0
dtype: int64

In [77]:
print(f"ext_service_name : {data['ext_service_name'].unique()}")
print(f"creative_width : {data['creative_width'].unique()}")
print(f"creative_height : {data['creative_height'].unique()}")
print(f"template_id : {data['template_id'].unique()}")
print(f"advertiser_name : {data['advertiser_name'].unique()}")
print(f"network_id : {data['network_id'].unique()}")
print(f"advertiser_currency : {data['advertiser_currency'].unique()}")
print(f"channel_name : {data['channel_name'].unique()}")
print(f"stats_currency : {data['stats_currency'].unique()}")
print(f"currency_code : {data['currency_code'].unique()}")
print(f"search_tag_cat : {data['search_tag_cat'].unique()}")
print(f"cmi_currency_code : {data['cmi_currency_code'].unique()}")
print(f"timezone : {data['timezone'].unique()}")
print(f"weekday_cat : {data['weekday_cat'].unique()}")
print(f"exchange_rate : {data['exchange_rate'].unique()}")

ext_service_name : ['Facebook Ads' 'DV360' 'Google Ads']
creative_width : [300.   0.  nan]
creative_height : [250.   0.  nan]
template_id : [90. 23. 92. 89. 93. nan]
advertiser_name : ['Web' 'Brand' 'Luxor' 'Almaza Bay' 'USA' 'Karnataka' 'Maharashtra' 'Oman'
 'UAE' 'Cairo' 'Al Ahmadi' 'Addis Ababa' 'Vadodara' 'Chennai' 'Coimbatore'
 'Malad' 'Indore' 'Pali' 'Andhra Pradesh' 'Kuala Lumpur' 'Gujarat'
 'Chandpur' 'West Bengal' 'Tamil Nadu' 'Madhya Pradesh' 'Orissa' 'North'
 'Thailand' 'Singapore' 'Sohar' 'KSA' 'Qatar' 'Muscat' 'Kuwait' 'Bahrain'
 'Malaysia' 'Jeddah' 'Chattogram' 'Pan India' 'Bangalore' 'Delhi'
 'Haryana' 'Punjab' 'UP']
network_id : [190 287 191 188 353 350]
advertiser_currency : ['SGD' 'USD' 'EGP' 'AED' 'INR']
channel_name : ['Mobile' 'Social' 'Video' 'Display' 'Search']
stats_currency : ['SGD' 'USD' 'EGP' 'AED' 'INR']
currency_code : ['SGD' 'USD' 'EGP' 'AED' 'INR']
search_tag_cat : ['Others' 'Youtube' 'Inmarket' 'Retargeting' 'Affinity']
cmi_currency_code : ['SGD' 'USD' 'EGP' 'AED' 'INR']
timezone : ['Asia/Singapore' 'America/New_York' 'Africa/Cairo' 'US/Eastern'
 'Asia/Kolkata' 'Asia/Muscat' 'Asia/Calcutta']
weekday_cat : ['week_end' 'week_day']
exchange_rate : [1]

Feature         |       int (Python built-in)     |     int64 (NumPy/Pandas)

Memory size     |        Dynamic (can grow)       |     Fixed at 64 bits (8 bytes)
Range of values | Unlimited (arbitrary precision) |     Limited to ±9.22e18
Performance     |    Slower (dynamic handling)    |     Faster (vectorized operations)
Common usage    |       General programming       |     DataFrames / Arrays

* Use int32 when you’re sure your values won’t exceed 2.1 billion → saves memory.
* Use int64 when values can get very large → avoids overflow errors.

# Pre-processing

In [79]:
data.drop(['ext_service_id', 'advertiser_id', 'channel_id', 'position_in_content', 'unique_reach', 'total_reach', 'network_margin', 'creative_width', 'creative_height', 'exchange_rate', 'cmi_currency_code','max_bid_cpm'], axis=1, inplace=True)

In [80]:
zero_days_campaign = data[data['no_of_days'] == 0]

In [81]:
zero_days_campaign

,campaign_item_id,no_of_days,time,ext_service_name,creative_id,search_tags,template_id,landing_page,advertiser_name,network_id,...,campaign_budget_usd,impressions,clicks,stats_currency,currency_code,media_cost_usd,search_tag_cat,timezone,weekday_cat,keywords
7430,2850,0,2022-07-11,Google Ads,1745,#Embrace Your Individuality with X,90.0,https://www.abcjewelry.com/collections/hoop-ea...,Almaza Bay,191,...,698.630688,1953,78,EGP,EGP,14.260242,Youtube,Africa/Cairo,week_day,holiday jewelry
7484,2850,0,2022-07-11,DV360,1750,#Embrace Your Individuality with X,90.0,https://www.abcjewelry.com/women/handmade-jewe...,Almaza Bay,191,...,598.780952,1035,8,EGP,EGP,11.049041,Youtube,Africa/Cairo,week_day,body chains
7551,2851,0,2022-07-11,Facebook Ads,1755,#The X Factor - Fashion for the Fearless,90.0,https://www.abcjewelry.com/collections/pearl-j...,Almaza Bay,191,...,498.984127,1082,9,EGP,EGP,10.075555,Youtube,Africa/Cairo,week_day,spring jewelry
7601,2879,0,2022-05-16,DV360,1760,#The Ultimate Fashion Statement with X,90.0,https://www.abcjewelry.com/collections/mixed-m...,USA,188,...,2300.000000,690,11,USD,USD,25.228439,Others,US/Eastern,week_day,toe rings
7646,3223,0,2022-08-01,Facebook Ads,1765,#Timeless X Style,90.0,https://www.abcjewelry.com/women/designer-insp...,USA,353,...,893.460490,522,7,AED,AED,0.898014,Inmarket,Asia/Kolkata,week_day,hair accessories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72414,3500,0,2022-11-17,Facebook Ads,15555,#The X Factor - Fashion for the Fearless,NaN,https://www.abcjewelry.com/collections/designe...,North,353,...,1839.813566,3895,130,INR,INR,33.276214,Others,Asia/Kolkata,week_day,chunky jewelry
72438,3532,0,2022-11-17,DV360,15560,#The Power of X,NaN,https://www.abcjewelry.com/collections/costume...,Orissa,353,...,367.962713,1042,28,INR,INR,5.769868,Others,Asia/Kolkata,week_day,personalized jewelry
72489,3558,0,2022-11-17,Google Ads,15575,#The X Factor - Fashion for the Fearless,NaN,https://www.abcjewelry.com/collections/handmad...,Chandpur,353,...,245.308475,787,11,INR,INR,2.948102,Others,Asia/Kolkata,week_day,party jewelry
72525,3559,0,2022-11-17,Google Ads,15585,#Be Bold. Be X,NaN,https://www.abcjewelry.com/women/affordable-je...,Tamil Nadu,353,...,1226.542377,2931,71,INR,INR,25.243827,Others,Asia/Kolkata,week_day,elegant jewelry
72562,3563,0,2022-11-17,DV360,15595,#The X Factor - Fashion for the Fearless,NaN,https://www.abcjewelry.com/collections/vintage...,Thailand,353,...,2085.122041,3947,176,INR,INR,41.076806,Others,Asia/Kolkata,week_day,arm cuffs

In [82]:
zero_media_usd = data[data['media_cost_usd'] == 0]

In [83]:
zero_media_usd['ext_service_name'].unique()
zero_media_usd['channel_name'].unique()

array(['Video', 'Search', 'Mobile', 'Social', 'Display'], dtype=object)

In [84]:
data['media_cost_usd'] = data['media_cost_usd'].replace(0, np.nan)

In [85]:
data['media_cost_usd'] = data.groupby('ext_service_name')['media_cost_usd']\
                             .transform(lambda x: x.fillna(x.mean()))

In [86]:
data['approved_budget'] = data.groupby(['no_of_days', 'advertiser_name'])['approved_budget'] \
                              .transform(lambda x: x.fillna(x.mean()))

In [87]:
conversion_rates = {
    'USD': 1.0,
    'SGD': 0.78,
    'AED': 0.2723,
    'EGP': 0.02078,
    'INR': 0.01136
}

data['approved_budget_usd'] = data['approved_budget'] * data['advertiser_currency'].map(conversion_rates)

🔹 When to use what
	•	transform → when you’re filling or adjusting values within groups (like filling missing budget by advertiser).
	•	apply → when you need a custom row-wise function (e.g., using multiple columns in the calculation).
	•	map → when you’re doing a simple one-to-one mapping on a Series (like currency → conversion rate).

In [88]:
data.drop(['advertiser_currency', 'stats_currency', 'currency_code'], axis=1, inplace = True)

In [89]:
data['time'] = pd.to_datetime(data['time'], errors='coerce')

	•	pd.to_datetime automatically detects the format (e.g. YYYY-MM-DD HH:MM:SS) and converts it to datetime64[ns].
	•	Once converted, you can extract parts like: 
        data['year'] = data['time'].dt.year
        data['month'] = data['time'].dt.month
        data['day'] = data['time'].dt.day
        data['hour'] = data['time'].dt.hour
        data['weekday'] = data['time'].dt.day_name()
    → invalid values become NaT (null datetime) using errors='coerce'
	•	If your time has a fixed format (e.g. "dd-mm-yyyy HH:MM:SS"), you can specify it for speed and accuracy: data['time'] = pd.to_datetime(data['time'], format='%d-%m-%Y %H:%M:%S')

In [90]:
data['campaign_item_id'] = data['campaign_item_id'].astype('int32')
data['no_of_days'] = data['no_of_days'].astype('int32')
data['creative_id'] = data['creative_id'].astype('int32')   
data['template_id'] = data['template_id'].astype('Int32')
data['approved_budget_usd'] = data['approved_budget_usd'].astype('float32')
data['campaign_budget_usd'] = data['campaign_budget_usd'].astype('float32')
data['impressions'] = data['impressions'].astype('int32')
data['clicks'] = data['clicks'].astype('int32')
data['media_cost_usd'] = data['media_cost_usd'].astype('float32')

since template_id has null values, trying to cast it directly with .astype('int32') will raise an error (Cannot convert non-finite values (NA or inf) to integer). If you want to keep nulls as-is, use Int32 (capital I) instead of int32.

In [91]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72612 entries, 0 to 72611
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   campaign_item_id     72612 non-null  int32
 1   no_of_days           72612 non-null  int32
 2   time                 72612 non-null  datetime64[ns]
 3   ext_service_name     72612 non-null  object
 4   creative_id          72612 non-null  int32
 5   search_tags          72612 non-null  object
 6   template_id          69200 non-null  Int32
 7   landing_page         72612 non-null  object
 8   advertiser_name      72612 non-null  object
 9   network_id           72612 non-null  int64
 10  approved_budget      72612 non-null  float64
 11  channel_name         72612 non-null  object
 12  campaign_budget_usd  72612 non-null  float32
 13  impressions          72612 non-null  int32
 14  clicks               72612 non-null  int32
 15  media_cost_usd       72612 non-null  float32
 16  search_tag_cat       72612 non-null  object
 17  timezone             72612 non-null  object
 18  weekday_cat          72612 non-null  object
 19  keywords             72612 non-null  object
 20  approved_budget_usd  72612 non-null  float32
dtypes: Int32(1), datetime64[ns](1), float32(3), float64(1), int32(5), int64(1), object(9)
memory usage: 9.2+ MB

In [92]:
zero_counts = (data == 0).sum()
zero_counts

campaign_item_id          0
no_of_days             1843
time                      0
ext_service_name          0
creative_id               0
search_tags               0
template_id               0
landing_page              0
advertiser_name           0
network_id                0
approved_budget           0
channel_name              0
campaign_budget_usd       0
impressions               0
clicks                    0
media_cost_usd            0
search_tag_cat            0
timezone                  0
weekday_cat               0
keywords                  0
approved_budget_usd       0
dtype: Int64

# Text Pre-processing

In [94]:
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/s.v.ssaisreenivas/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [95]:
def extract_keywords(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    keywords = [w for w in words if w not in stop_words]
    return keywords

In [96]:
data['important_tags'] = data['search_tags'].apply(extract_keywords)

In [97]:
data.head()

,campaign_item_id,no_of_days,time,ext_service_name,creative_id,search_tags,template_id,landing_page,advertiser_name,network_id,...,campaign_budget_usd,impressions,clicks,media_cost_usd,search_tag_cat,timezone,weekday_cat,keywords,approved_budget_usd,important_tags
0,2733,7,2022-05-01,Facebook Ads,1000,#The Power of X,90,https://www.abcjewelry.com/collections/boho-je...,Web,190,...,652.173889,837,8,14.058514,Others,Asia/Singapore,week_end,delicate bracelets,312.0,"[power, x]"
1,2733,8,2022-05-02,DV360,1000,#Be Bold. Be X,90,https://www.abcjewelry.com/women/costume-jewelry/,Web,190,...,652.173889,2634,44,99.633499,Others,Asia/Singapore,week_day,summer jewelry,312.0,"[bold, x]"
2,2733,9,2022-05-03,Facebook Ads,1000,#Embrace Your Individuality with X,90,https://www.abcjewelry.com/collections/boho-je...,Web,190,...,652.173889,2135,32,109.419678,Others,Asia/Singapore,week_day,artisan jewelry,312.0,"[embrace, individuality, x]"
3,2733,10,2022-05-04,Facebook Ads,1000,#Be Bold. Be X,90,https://www.abcjewelry.com/collections/rhinest...,Web,190,...,652.173889,2327,48,115.209496,Others,Asia/Singapore,week_day,layered bracelets,312.0,"[bold, x]"
4,2733,11,2022-05-05,Google Ads,1000,#Be Bold. Be X,90,https://www.abcjewelry.com/collections/boho-je...,Web,190,...,652.173889,1538,20,66.990105,Others,Asia/Singapore,week_day,minimalist jewelry,312.0,"[bold, x]"

In [98]:
username = "postgres"         
password = "8919734777.Svs"
host = "localhost"
port = "5432"                  
database = "marketing_db"
table_name = "marketing_data"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}",
    connect_args={'connect_timeout': 5, 'sslmode': 'disable'}
)

try:
    with engine.connect() as conn:
        print("Connected")
except Exception as e:
    print("Not Connected:", e)

Connected

In [99]:
data.to_sql(
    name=table_name,
    con=engine,
    if_exists='replace',  
    index=False
)

print("Data uploaded")

Data uploaded